### ISSUE TITLE
Does it support GGUF (instead of GGML)?

### ISSUE THREAD

**Issue by Duxon** [Bip-Rep/sherpa#20]
New small models (like Mistral) are not available as GGML, but GGUF. Does Sherpa plan to support this?

**Comment by danemadsen** [comment]
Hello, I think this repo has been abandoned. I have forked sherpa out and taken over development to add GGUF support and a better UI. you can download it here:

https://github.com/danemadsen/maid

currently only android and linux are supported.

**Comment by Duxon** [comment]
Looks great and I'll give it a try. The Maid repo doesn't feature an issues board. How can I give feedback? @danemadsen

**Comment by danemadsen** [comment]
> Looks great and I'll give it a try. The Maid repo doesn't feature an issues board. How can I give feedback? @danemadsen 

I'll look into it, It did have an issue board before when I didn't have it attached to sherpa as a fork. Perhaps I can contact github and get them to add an issue board for me. 

Worst comes to worse I can detach it from sherpa later.

For the time being though I want to keep it attached as a fork because I want to capture people who come to Sherpa's repo. 

EDIT: Never mind, i worked out how to add and issue and discussion board for you
